# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            ##正式主库数据源
#            master:
#                url: jdbc:mysql://192.168.4.191:3306/miracle?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
#                username: root
#                password: sanco@mysql


            # 测试主库数据源
            # mes测试服务器
            master:
                url: jdbc:mysql://192.168.4.240:3306/miracle?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: Sanco#Mes1=


            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: true
                url: jdbc:sqlserver://192.168.4.71:1433;databaseName=SC;trustServerCertificate=true;encrypt=true;
                username: bs_guest
                password: bs_guest@123

            #从数据源2
            slave2:
                # 从数据源开关/默认关闭
                enabled: true
                url: jdbc:sqlserver://192.168.4.191:17933;databaseName=SCYCDATA;trustServerCertificate=true;encrypt=true;
                username: sa
                password: 1234!QAZ2wsx

##            #从数据源2
#            slave2:
#                # 从数据源开关/默认关闭
#                enabled: true
#                url: jdbc:sqlserver://192.168.4.69:1433;databaseName=SC;trustServerCertificate=true;encrypt=true;
#                username: sa
#                password: 1234!QAZ2wsx

            #从数据库3
            #mes对接欣旺达
            slave3:
                # 从数据源开关/默认关闭
                enabled: true
                url: jdbc:mysql://192.168.4.121:3306/mom_qms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: Sanco#Mes1=

            #从数据库4
            #纸飞机
            slave4:
                enabled: true
                url: jdbc:sqlserver://192.168.4.226:1433;databaseName=SancoERP;trustServerCertificate=true;encrypt=true;
                username: mes
                password: Mes@2025

            #从数据库5
            #纸飞机2
            slave5:
                enabled: true
                url: jdbc:sqlserver://192.168.4.226:1433;databaseName=DataSyncs;trustServerCertificate=true;encrypt=true;
                username: mes
                password: Mes@2025

            # 初始连接数
            initialSize: 10
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置连接超时时间
            connectTimeout: 30000
            # 配置网络超时时间
            socketTimeout: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: miracle
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true